#include <stdint.h>
#include "Colours.h"

#define MENU_SEP 2

#define SELECTED_COLOUR ETC_GREEN
#define NOT_SELECTED_COLOUR RED
#define SELECTED_TEXT_COLOUR WHITE
#define NOT_SELECTED_TEXT_COLOUR DARK_GREY
#define BACKGROUND_COLOUR BLACK