// INITR_BLACKTAB
#define GRAY 0xe71c
#define GOLD 0xd560
#define RED 0xf800
#define BLUE 0x1f
#define LIGHT_BLUE 0x75d
#define DARK_BLUE 0x33b
#define DARK_GREY 0x4a49
#define PURPLE 0xb01b
#define GREEN 0x4a0
#define SALMON 0xed08
#define WHITE 0xffff
#define BLACK 0x0
#define PINK 0xf81b
#define LIGHTNING_BLUE 0x75c
#define NIGHT_BLUE 0x1d4
#define MOON_YELLOW 0xd660
#define HOT_PINK 0xf81a
#define ORANGE 0xfbc0
#define VIOLET 0x63fd
#define ETC_GREEN 0x64a

#define LIGHT_GREEN 0x7e0
#define LIGHT_RED 0xf8c3

// for coins
#define BTC_FOREGROUND 0xFFFF
#define BTC_BACKGROUND 0xF483

#define ETH_FOREGROUND 0xC67E
#define ETH_BACKGROUND 0x63FD

#define USDT_FOREGROUND 0xFFFF
#define USDT_BACKGROUND 0x5572

#define BNB_FOREGROUND 0xFFFF
#define BNB_BACKGROUND 0xF5C1

#define SOL_FOREGROUND 0x1F15
#define SOL_BACKGROUND 0x0000

#define USDC_FOREGROUND 0xFFFF
#define USDC_BACKGROUND 0x23B9

#define XRP_FOREGROUND 0x2145
#define XRP_BACKGROUND 0xFFFF

#define TON_FOREGROUND 0xFFFF
#define TON_BACKGROUND 0x0459

#define DOGE_FOREGROUND 0xFFFF
#define DOGE_BACKGROUND 0xC526

#define TRX_FOREGROUND 0xFFFF
#define TRX_BACKGROUND 0xF800

#define ADA_FOREGROUND 0x0195
#define ADA_BACKGROUND 0xFFFF

#define AVAX_FOREGROUND 0xFFFF
#define AVAX_BACKGROUND 0xDA28

#define SHIB_FOREGROUND 0xFD20
#define SHIB_BACKGROUND 0xF8E2

#define LINK_FOREGROUND 0x2ADB
#define LINK_BACKGROUND 0xFFFF

#define BCH_FOREGROUND 0xFFFF
#define BCH_BACKGROUND 0x0E11

#define DOT_FOREGROUND 0xE00F
#define DOT_BACKGROUND 0xFFFF

#define LEO_FOREGROUND 0xF666
#define LEO_BACKGROUND 0x10E3

#define UNI_FOREGROUND 0xF80F
#define UNI_BACKGROUND 0xFFFF

#define NEAR_FOREGROUND 0x0000
#define NEAR_BACKGROUND 0xFFFF

#define DAI_FOREGROUND 0xFFFF
#define DAI_BACKGROUND 0xF566
